package AcseleV13_8.tests;

import AcseleV13_8.beans.EmisionPrimaEmitidaBean;
import org.apache.log4j.Logger;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import util.DataSetManager;

import java.sql.SQLException;
import java.util.ArrayList;

/**
 * Created by kzambrano on 29/09/2016.
 */
public class VistaEmisionPrimaEmitidaTest {

    private final static Logger log = Logger.getLogger(VistaTercerosDocumentosTest.class);

    @Test
    public void mainTest() {

        ArrayList openItemPrimaEmision = null;

        try {
            openItemPrimaEmision = EmisionPrimaEmitidaBean.getEmisionPrimaEmitida();
        }catch (SQLException e) {
            log.error(e);
        }

        for(int i = 0; i < openItemPrimaEmision.size(); i++) {

            EmisionPrimaEmitidaBean emisionPrimaEmitidaBean = (EmisionPrimaEmitidaBean) openItemPrimaEmision.get(i);
            EmisionPrimaEmitida a = new EmisionPrimaEmitida();

            try {
                a.testLink(emisionPrimaEmitidaBean, i);
            } catch (Exception e) {
                e.printStackTrace();
                log.info("Test Case - " + a.nombreAutomatizacion + " - " + e);
            }
        }

    }

    @Before
    public void setUp() throws Exception {

        /*DataSetManager.createPartialDataSet("SELECT PRUEBA, PRODUCTO, VIGENCIA, FECHA_DESDE  ,FECHA_HASTA  ,EVENTO_APLICAR  ,FECHA_MOVIMIENTO  ,FECHA_EFECTIVA_APLICA_EVENTO  ,PLAN_FINANCIAMIENTO  ,MONEDA  ,SUCURSAL  ,NUMERO_POLIZA  ,FECHA_EMISION  ,TIPO_PRODUCCION ,PERIODO_GRACIA  ,LINEA_CREDITO  ,HORA_INICIACION_VENCIMIENTO  ,UNIDAD_NEGOCIO  ,CANAL_VENTA  ,FRECUENCIA_PAGO  ,TIPO_POLIZA ,TIPO_VALOR_ASEGURADO  ,NIVEL_AGRUPAMIENTO_REASEGURO  ,TOMADOR_NOMBRE1, TOMADOR_NOMBRE2, TOMADOR_APELLIDO1, TOMADOR_APELLIDO2 ,PORCENTAJE_PARTICIPA_TOMADOR  ,NUMERO_UNIDAD_RIESGO  ,NUMERO_CREDITO  ,MONTO_ASEGURADO  ,FACTOR_VIDA  ,VALOR_SEGURO_PRIMA  ,FECHA_DESEMBOLSO  ,VALOR_PRESTAMO  ,CUOTAS_PACTADAS  ,SALDO_CAPITAL  ,ESTADO_CREDITO  ,CUOTAS_MORA ,FECHA_PROCESO  ,FECHA_PAGO  ,CUOTA_PAGADA  ,FECHA_MORA  ,PORCENTAJE_FACULTATIVO  ,NUMERO_OBJETO_ASEG  ,ASEGURADO_PRIMARIO  ,PORCENTAJE_EXTRA_PRIMA  ,PORCENTAJE_DESCUENTO  ,EDAD_ASEGURADO  ,NOMBRE_COMPLETO_ASEGURADO  ,NUM_OBJ_ASEG_CONTENIDOS_UR  ,DOCUMENTO_IDENTIDAD_ASEGURADO  ,FECHA_NACIMIENTO_ASEGURADO  ,DIRECCION_ASEGURADO  ,TELEFONO_FIJO  ,DEPARTAMENTO  ,CIUDAD  ,ASEGURADO_VIDA_NOMBRE1  ,PORCEN_PARTICIPA_ASEG_VIDA  ,TIPO_TERCERO, ASEGURADO_VIDA_NOMBRE2, ASEGURADO_VIDA_APELLIDO1, ASEGURADO_VIDA_APELLIDO2, BENEFICIARIO_NATURAL_NOMBRE1, BENEFICIARIO_NATURAL_NOMBRE2, BENEFICIARIO_NATURAL_APELLIDO1, BENEFICIARIO_NATURAL_APELLIDO2, TIPO_BENEFICIARIO, BENEFICIARIO_IRREVOCABLE, PORCEN_PARTICIP_BENEF_NATURAL, CODIGO_BENEFICIARIO, PARENTESCO FROM EMISION_PRIMA_EMITIDA ORDER BY PRUEBA ASC",
                "EMISION_PRIMA_EMITIDA",
                "C:/AcseleTests/AutomationTestAcsele/src/AcseleV13_8/tests/xmls/emisionPrimaEmitida_dataset.xml");

        DataSetManager.createPartialDataSet("SELECT PRUEBA, PRODUCTO, VIGENCIA, FECHA_DESDE  ,FECHA_HASTA  ,EVENTO_APLICAR  ,FECHA_MOVIMIENTO  ,FECHA_EFECTIVA_APLICA_EVENTO  ,PLAN_FINANCIAMIENTO  ,MONEDA  ,SUCURSAL  ,NUMERO_POLIZA  ,FECHA_EMISION  ,TIPO_PRODUCCION ,PERIODO_GRACIA  ,LINEA_CREDITO  ,HORA_INICIACION_VENCIMIENTO  ,UNIDAD_NEGOCIO  ,CANAL_VENTA  ,FRECUENCIA_PAGO  ,TIPO_POLIZA ,TIPO_VALOR_ASEGURADO  ,NIVEL_AGRUPAMIENTO_REASEGURO  ,TOMADOR_NOMBRE1, TOMADOR_NOMBRE2, TOMADOR_APELLIDO1, TOMADOR_APELLIDO2 ,PORCENTAJE_PARTICIPA_TOMADOR  ,NUMERO_UNIDAD_RIESGO  ,NUMERO_CREDITO  ,MONTO_ASEGURADO  ,FACTOR_VIDA  ,VALOR_SEGURO_PRIMA  ,FECHA_DESEMBOLSO  ,VALOR_PRESTAMO  ,CUOTAS_PACTADAS  ,SALDO_CAPITAL  ,ESTADO_CREDITO  ,CUOTAS_MORA ,FECHA_PROCESO  ,FECHA_PAGO  ,CUOTA_PAGADA  ,FECHA_MORA  ,PORCENTAJE_FACULTATIVO  ,NUMERO_OBJETO_ASEG  ,ASEGURADO_PRIMARIO  ,PORCENTAJE_EXTRA_PRIMA  ,PORCENTAJE_DESCUENTO  ,EDAD_ASEGURADO  ,NOMBRE_COMPLETO_ASEGURADO  ,NUM_OBJ_ASEG_CONTENIDOS_UR  ,DOCUMENTO_IDENTIDAD_ASEGURADO  ,FECHA_NACIMIENTO_ASEGURADO  ,DIRECCION_ASEGURADO  ,TELEFONO_FIJO  ,DEPARTAMENTO  ,CIUDAD  ,ASEGURADO_VIDA_NOMBRE1  ,PORCEN_PARTICIPA_ASEG_VIDA  ,TIPO_TERCERO, ASEGURADO_VIDA_NOMBRE2, ASEGURADO_VIDA_APELLIDO1, ASEGURADO_VIDA_APELLIDO2, BENEFICIARIO_NATURAL_NOMBRE1, BENEFICIARIO_NATURAL_NOMBRE2, BENEFICIARIO_NATURAL_APELLIDO1, BENEFICIARIO_NATURAL_APELLIDO2, TIPO_BENEFICIARIO, BENEFICIARIO_IRREVOCABLE, PORCEN_PARTICIP_BENEF_NATURAL, CODIGO_BENEFICIARIO, PARENTESCO FROM EMISION_PRIMA_EMITIDA ORDER BY PRUEBA ASC",
                "EMISION_PRIMA_EMITIDA",
                "C:/AcseleTests/AutomationTestAcsele/target/classes/AcseleV13_8/tests/xmls/emisionPrimaEmitida_dataset.xml");
*/
        DataSetManager.loadDataSet("/AcseleV13_8/tests/xmls/emisionPrimaEmitida_dataset.xml", DataSetManager.REFRESH_OPERATION);
    }

    @After
    public void tearDown() throws Exception {

        DataSetManager.loadDataSet("/AcseleV13_8/tests/xmls/emisionPrimaEmitida_dataset.xml", DataSetManager.DELETE_OPERATION);
    }

}
